/**
 * @fileoverview Virtual assistant chat popup component.
 * Manages user input, displays AI responses with typewriter animations, 
 * and handles UI states such as auto-scrolling and loading indicators.
 */

import React, { useState, useEffect, useRef, useCallback, useMemo, memo } from "react";
import {
  Box,
  Paper,
  Typography,
  Avatar,
  Stack,
  useTheme,
  alpha,
  Portal,
  CircularProgress,
  Slide,
} from "@mui/material";
import { keyframes } from "@mui/system";
import { Send, Bot, X } from "lucide-react";
import { useMutation } from "@tanstack/react-query";
import { useForm, Controller } from "react-hook-form";
import parse from "html-react-parser";

import { askAssistant } from "../../service/assistant-service";
import { IconButton, FilledButton, AppInput } from "@heykyy/components";

/**
 * Keyframes for the bouncing dot animation used in the typing indicator.
 * Creates a wave-like jumping effect for three consecutive dots.
 */
const dotJumpAnimation = keyframes`
  0%, 80%, 100% { transform: translateY(0); opacity: 0.3; }
  40% { transform: translateY(-8px); opacity: 1; }
`;

/**
 * A floating chat interface component that renders a conversational UI for the AI assistant.
 * Utilizes an MUI Portal to break out of the standard DOM hierarchy, ensuring it renders
 * above all other elements. Includes scroll management, responsive sizing, and typing animations.
 *
 * @param {object} props - Component properties.
 * @param {boolean} props.isOpen - Controls the visibility and mount state of the slide-in animation.
 * @param {Function} props.onClose - Callback triggered when the close icon is clicked.
 * @returns {JSX.Element|null} The rendered chat portal or null if the visibility state is false.
 */
const FabFade = ({ isOpen, onClose }) => {
  const { palette, shape, zIndex } = useTheme();
  
  const [messages, setMessages] = useState([]);
  const [isTyping, setTyping] = useState(false);
  const [streamedText, setStreamedText] = useState("");
  
  const scrollRef = useRef(null);
  const typingTimeoutRef = useRef(null);

  const { control, handleSubmit, reset, watch } = useForm({
    defaultValues: { message: "" },
  });

  const messageValue = watch("message");

  /**
   * Automatically scrolls the chat view to the bottom.
   * Called whenever a new message is added or during the typing animation
   * to ensure the latest content always stays in the user's viewport.
   */
  const scrollToBottom = useCallback(() => {
    scrollRef.current?.scrollIntoView({ behavior: "smooth" });
  }, []);

  /**
   * Parses and formats the HTML string returned by the AI into React elements.
   * Applies specific MUI typography styles to ensure lists, paragraphs, and links
   * adhere to the chat interface's design system (e.g., overriding default margins for tighter spacing).
   *
   * @param {string} htmlContent - The raw HTML string generated by the AI assistant.
   * @returns {JSX.Element} The formatted and styled React nodes ready for rendering inside the chat bubble.
   */
  const formatBotMessage = useCallback(
    (htmlContent) => (
      <Box
        sx={{
          fontSize: "0.875rem",
          lineHeight: 1.6,
          "& p": { m: 0, mb: 1 },
          "& p:last-child": { mb: 0 },
          "& ul, & ol": { m: 0, pl: 2, mb: 1 },
          "& li": { mb: 0.5 },
          "& a": {
            color: palette.primary.main,
            fontWeight: 600,
            textDecoration: "none",
          },
        }}
      >
        {parse(htmlContent)}
      </Box>
    ),
    [palette.primary.main]
  );

  /**
   * Simulates a human-like typing animation for the AI's response.
   * Iterates through the provided string character by character with a slight delay (8ms),
   * updating the streamed text state to create the visual typing effect before pushing
   * the final, complete message object to the main chat history array.
   *
   * @param {string} fullText - The complete response string to be animated.
   */
  const startTypingEffect = useCallback((fullText) => {
    setTyping(true);
    let index = 0;
    setStreamedText("");

    const typeWriter = () => {
      if (index < fullText.length) {
        setStreamedText((prev) => prev + fullText.charAt(index));
        index++;
        typingTimeoutRef.current = setTimeout(typeWriter, 8);
      } else {
        setMessages((prev) => [...prev, { text: fullText, from: "bot" }]);
        setStreamedText("");
        setTyping(false);
      }
    };
    typeWriter();
  }, []);

  const mutation = useMutation({
    mutationFn: (msg) => askAssistant(msg),
    onSuccess: (message) => {
      if (message) {
        startTypingEffect(message);
      }
    },
    onError: (error) => {
      setTyping(false);
      const errorMsg = error?.errors || "An error occurred";
      setMessages((prev) => [
        ...prev,
        {
          text: `<span style="color: ${palette.error.main}">${errorMsg}</span>`,
          from: "bot",
        },
      ]);
    },
  });

  /**
   * Handles the submission of the chat input form.
   * Validates the input to prevent empty messages or submissions while a previous
   * request/animation is still processing. Instantly appends the user's message to the UI
   * for immediate visual feedback and triggers the API mutation to fetch the AI's response.
   *
   * @param {object} formData - The data object provided by react-hook-form containing the 'message' string.
   */
  const onSubmit = useCallback(
    (formData) => {
      const userMessage = formData.message?.trim();
      if (!userMessage || isTyping || mutation.isPending) return;

      setMessages((prev) => [...prev, { text: userMessage, from: "user" }]);
      reset({ message: "" });
      mutation.mutate(userMessage);
    },
    [isTyping, mutation, reset]
  );

  useEffect(() => {
    if (isOpen && messages.length === 0) {
      setMessages([
        {
          text: "<p>Hello! I'm Rivo, Rifky Firmansyah's official AI guide. How can I help you today?</p>",
          from: "bot",
        },
      ]);
    }
  }, [isOpen, messages.length]);

  useEffect(() => {
    scrollToBottom();
  }, [messages, streamedText, isTyping, scrollToBottom]);

  useEffect(() => {
    return () => {
      if (typingTimeoutRef.current) {
        clearTimeout(typingTimeoutRef.current);
      }
    };
  }, []);

  const paperStyles = useMemo(
    () => ({
      width: { xs: "100%", sm: 380 },
      height: { xs: "100dvh", sm: 540 },
      position: "fixed",
      bottom: { xs: 0, sm: 10 },
      right: { xs: 0, sm: 20 },
      zIndex: zIndex.tooltip + 100,
      display: "flex",
      flexDirection: "column",
      overflow: "hidden",
      border: "none",
      borderRadius: { xs: 0, sm: "24px" },
      backgroundColor: alpha(palette.background.paper, 0.9),
      backdropFilter: "blur(20px)",
      boxShadow: `0 12px 48px ${alpha(palette.common.black, 0.15)}`,
    }),
    [palette.background.paper, palette.common.black, zIndex.tooltip]
  );

  if (!isOpen) return null;

  return (
    <Portal>
      <Slide direction="up" in={isOpen} mountOnEnter unmountOnExit>
        <Paper sx={paperStyles} elevation={0}>
          <Box
            sx={{
              p: 2.5,
              pt: { xs: "calc(20px + env(safe-area-inset-top))", sm: 2.5 },
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
            }}
          >
            <Stack direction="row" spacing={1.5} alignItems="center">
              <Avatar
                sx={{
                  bgcolor: palette.primary.main,
                  width: 36,
                  height: 36,
                }}
              >
                <Bot size={20} color={palette.primary.contrastText} />
              </Avatar>
              <Box>
                <Typography variant="subtitle1" fontWeight={700} lineHeight={1.2}>
                  Rivo
                </Typography>
                <Typography variant="caption" sx={{ color: palette.text.secondary }}>
                  Online
                </Typography>
              </Box>
            </Stack>
            {/* FIXED: changed size from "xs" to "extraSmall" based on IconButton config */}
            <IconButton size="extraSmall" onClick={onClose} icon={<X size={20} />} />
          </Box>

          <Box
            sx={{
              flex: 1,
              overflowY: "auto",
              p: 2,
              px: 2.5,
            }}
          >
            <Stack spacing={2.5}>
              {messages.map((msg, index) => (
                <Box
                  key={index}
                  sx={{
                    display: "flex",
                    justifyContent: msg.from === "user" ? "flex-end" : "flex-start",
                    gap: 1.5,
                  }}
                >
                  <Box
                    sx={{
                      maxWidth: "85%",
                      p: 2,
                      borderRadius: "20px",
                      bgcolor:
                        msg.from === "user"
                          ? palette.primary.main
                          : palette.mode === "dark"
                          ? alpha(palette.common.white, 0.05)
                          : alpha(palette.common.black, 0.03),
                      color:
                        msg.from === "user"
                          ? palette.primary.contrastText
                          : palette.text.primary,
                      borderBottomRightRadius: msg.from === "user" ? "4px" : "20px",
                      borderBottomLeftRadius: msg.from === "bot" ? "4px" : "20px",
                    }}
                  >
                    {msg.from === "bot" ? (
                      formatBotMessage(msg.text)
                    ) : (
                      <Typography variant="body2" sx={{ fontWeight: 500 }}>
                        {msg.text}
                      </Typography>
                    )}
                  </Box>
                </Box>
              ))}

              {(isTyping || mutation.isPending) && (
                <Box sx={{ display: "flex", gap: 1.5 }}>
                  <Box
                    sx={{
                      p: 2,
                      borderRadius: "20px",
                      borderBottomLeftRadius: "4px",
                      bgcolor:
                        palette.mode === "dark"
                          ? alpha(palette.common.white, 0.05)
                          : alpha(palette.common.black, 0.03),
                      minWidth: 60,
                    }}
                  >
                    {!streamedText ? (
                      <Box
                        sx={{
                          display: "flex",
                          gap: 0.8,
                          alignItems: "center",
                          height: 20,
                        }}
                      >
                        {[0, 0.2, 0.4].map((d) => (
                          <Box
                            key={d}
                            sx={{
                              width: 6,
                              height: 6,
                              bgcolor: palette.primary.main,
                              borderRadius: "50%",
                              animation: `${dotJumpAnimation} 1.4s infinite ease-in-out ${d}s`,
                            }}
                          />
                        ))}
                      </Box>
                    ) : (
                      formatBotMessage(streamedText)
                    )}
                  </Box>
                </Box>
              )}
              <div ref={scrollRef} />
            </Stack>
          </Box>

          <Box
            component="form"
            onSubmit={handleSubmit(onSubmit)}
            sx={{
              p: 2.5,
              pb: { xs: "calc(20px + env(safe-area-inset-bottom))", sm: 2.5 },
              display: "flex",
              gap: 1.5,
              alignItems: "center",
            }}
          >
            <Controller
              name="message"
              control={control}
              render={({ field }) => (
                <AppInput
                  {...field}
                  placeholder="Ask Rivo something..."
                  disabled={mutation.isPending || isTyping}
                  autoComplete="off"
                  sx={{
                    "& .MuiOutlinedInput-root": {
                      bgcolor:
                        palette.mode === "dark"
                          ? alpha(palette.common.white, 0.05)
                          : alpha(palette.common.black, 0.03),
                      borderRadius: "16px",
                      border: "none",
                      "& fieldset": { border: "none" },
                    },
                  }}
                />
              )}
            />
            {/* FIXED: Kept size prop to default 'medium' behavior or it will inherit base properties */}
            <FilledButton
              type="submit"
              disabled={!messageValue?.trim() || mutation.isPending || isTyping}
              sx={{
                minWidth: 48,
                width: 48,
                height: 48,
                borderRadius: "16px",
                p: 0,
                boxShadow: `0 4px 12px ${alpha(palette.primary.main, 0.3)}`,
              }}
            >
              {mutation.isPending ? (
                <CircularProgress size={20} color="inherit" />
              ) : (
                <Send size={20} />
              )}
            </FilledButton>
          </Box>
        </Paper>
      </Slide>
    </Portal>
  );
};

export default memo(FabFade);