/**
 * @typedef {Object} AiBlogResponse
 * @property {string} title
 * @property {string} summary
 * @property {string} contentHtml
 * @property {string[]} tags
 * @property {string} metaTitle
 * @property {string} metaDesc
 */

/**
 * @typedef {Object} AiProjectResponse
 * @property {string} title
 * @property {string} summary
 * @property {string} contentHtml
 * @property {string} metaTitle
 * @property {string} metaDesc
 */

/**
 * DTO for AI-generated Blog content.
 * Ensures the AI response is normalized with safe fallback values.
 */
class GeneratedBlogDto {
    /**
     * @param {AiBlogResponse} data - The parsed JSON object from AI.
     */
    constructor(data) {
      this.title = data?.title || "Untitled Blog Post";
      this.summary = data?.summary || "";
      this.content = data?.contentHtml || "";
      this.tags = Array.isArray(data?.tags) ? data.tags : [];
      
      this.meta = {
        title: data?.metaTitle || data?.title || "",
        description: data?.metaDesc || data?.summary || "",
      };
    }
  }
  
  /**
   * DTO for AI-generated Project Case Studies.
   * Normalizes storytelling content for project portfolios.
   */
  class GeneratedProjectDto {
    /**
     * @param {AiProjectResponse} data - The parsed JSON object from AI.
     */
    constructor(data) {
      this.title = data?.title || "Untitled Project Project";
      this.summary = data?.summary || "";
      this.content = data?.contentHtml || "";
      
      this.meta = {
        title: data?.metaTitle || data?.title || "",
        description: data?.metaDesc || data?.summary || "",
      };
    }
  }
  
  /**
   * DTO for Personal Assistant Chat responses.
   * Specifically handles the communication between Rivo (AI) and the user.
   */
  class AssistantChatDto {
    /**
     * @param {string} answer - The raw HTML string generated by the AI.
     */
    constructor(answer) {
      /** * The conversational response formatted in safe HTML.
       * @type {string} 
       */
      this.answer = answer || "<p>Maaf, saya tidak bisa memproses pertanyaan tersebut saat ini.</p>";
      
      /** * Timestamp for the chat interaction.
       * @type {Date} 
       */
      this.timestamp = new Date();
    }
  }
  
  export { GeneratedBlogDto, GeneratedProjectDto, AssistantChatDto };