// palette.js
export const LightPalette = Object.freeze({
  cms: {
    background: "#f8f8f8",           // putih-abuan untuk CMS
    foreground: "#2c2c2c",           // tidak terlalu pekat
    card: "#ffffff",
    cardForeground: "#2c2c2c",       // teks card lebih lembut
    popover: "#ffffff",
    popoverForeground: "#2c2c2c",
    primary: "#1a1a1a",              // utama tapi lembut
    primaryForeground: "#ffffff",
    secondary: "#f4f4f5",
    secondaryForeground: "#4a4a4a",   // sekunder lebih lembut
    accent: "#e6e6e6",
    accentForeground: "#2c2c2c",
    muted: "#f6f6f6",
    mutedForeground: "#7a7a7a",
    destructive: "#3b3b3b",
    destructiveForeground: "#ffffff",
    border: "#e6e6e6",
    input: "#ffffff",
    ring: "#1a1a1a",
    info: "#3b3b3b",
    success: "#292929",
    warning: "#555555",
  },
  frontend: {
    background: "#ffffff",
    foreground: "#0e0e0e",
    card: "#ffffff",
    cardForeground: "#0e0e0e",
    popover: "#ffffff",
    popoverForeground: "#0e0e0e",
    primary: "#0e0e0e",
    primaryForeground: "#ffffff",
    secondary: "#f4f4f5",
    secondaryForeground: "#0e0e0e",
    accent: "#e6e6e6",
    accentForeground: "#0e0e0e",
    muted: "#f6f6f6",
    mutedForeground: "#727272",
    destructive: "#3b3b3b",
    destructiveForeground: "#ffffff",
    border: "#e6e6e6",
    input: "#ffffff",
    ring: "#0e0e0e",
    info: "#3b3b3b",
    success: "#292929",
    warning: "#555555",
  },
});

export const DarkPalette = Object.freeze({
  cms: {
    background: "#1a1a1a",          // CMS dark sedikit terang
    foreground: "#d4d4d4",          // teks lebih lembut
    card: "#151515",
    cardForeground: "#d4d4d4",
    popover: "#1a1a1a",
    popoverForeground: "#d4d4d4",
    primary: "#e0e0e0",
    primaryForeground: "#0e0e0e",
    secondary: "#1f1f1f",
    secondaryForeground: "#b0b0b0",
    accent: "#292929",
    accentForeground: "#d4d4d4",
    muted: "#1a1a1a",
    mutedForeground: "#8c8c8c",
    destructive: "#3b3b3b",
    destructiveForeground: "#e6e6e6",
    border: "#333333",
    input: "#1a1a1a",
    ring: "#727272",
    info: "#8c8c8c",
    success: "#a4a4a4",
    warning: "#555555",
  },
  frontend: {
    background: "#0e0e0e",
    foreground: "#e6e6e6",
    card: "#151515",
    cardForeground: "#e6e6e6",
    popover: "#1a1a1a",
    popoverForeground: "#e6e6e6",
    primary: "#e6e6e6",
    primaryForeground: "#0e0e0e",
    secondary: "#1f1f1f",
    secondaryForeground: "#e6e6e6",
    accent: "#292929",
    accentForeground: "#e6e6e6",
    muted: "#1a1a1a",
    mutedForeground: "#8c8c8c",
    destructive: "#3b3b3b",
    destructiveForeground: "#e6e6e6",
    border: "#333333",
    input: "#1a1a1a",
    ring: "#727272",
    info: "#8c8c8c",
    success: "#a4a4a4",
    warning: "#555555",
  },
});
